### ISSUE TITLE
Crash when trying to create a new character

### ISSUE THREAD

**Issue by UTengine** [stevewgr/ko#36] opened 2022-07-18 18:20 UTC
#### Description
Character Create Gameprocedure and character create UI.
I'm not sure where it goes wrong, when it reads the tbl it explodes. I can jump out of it and proceed and select warrior then it will say erace barbarian but the stats don't get displayed thus tbl doesnt get read correctly. I'm sure its missing data types.
Openko has had it too, but i can't even get that far.
https://github.com/srmeier/KnightOnline/issues/122

#### Screenshots
https://cdn.discordapp.com/attachments/388230610012864512/998612212493078718/Knight_Online_2022.07.18_-_17.27.36.01.mp4

#### Files
tbl: NewChrValue.tbl
client: https://www.mediafire.com/file/ukkvu69gxee1bh5/client_bin.rar/file
#### To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] DataTypes
- [ ] Maybe server
- [ ] IDK maybe i took too much on my plate to chew we can return back to older data types and older chrvalue.tbl ..... You can pick

**Comment by stevewgr** [comment] 2022-08-10 22:07
Hi @UTengine,
Thanks for the detailed report.
It looks like this was never an issue with the base that we use.
I suppose you were using something else or changes that were not part of this code base.
As this issue could not be reproduced and I'm able to create characters without issues, I'll close this ticket as not doing.

**Closed** 2022-08-10 22:09 UTC
